PRINT '--- Cədvəllərin və Əlaqələrin Yaradılması Başladı ---';

-- Əsas və Köməkçi Cədvəllər
CREATE TABLE rollar ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(50) UNIQUE NOT NULL, tesvir NVARCHAR(255) NULL, yaradilma_tarixi DATETIME DEFAULT GETDATE() NOT NULL, son_deyisiklik DATETIME NULL );
CREATE TABLE istifadeciler ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(50) NOT NULL, soyad NVARCHAR(50) NOT NULL, istifadeci_adi NVARCHAR(50) UNIQUE NOT NULL, parol_hash NVARCHAR(512) NOT NULL, parol_salt NVARCHAR(128) NOT NULL, rol_id INT NOT NULL, aktivdir BIT DEFAULT 1 NOT NULL, son_giris_tarixi DATETIME NULL, yaradilma_tarixi DATETIME DEFAULT GETDATE() NOT NULL, deaktivasiya_tarixi DATETIME NULL );
CREATE TABLE emeliyyat_jurnali ( id INT PRIMARY KEY IDENTITY(1,1), istifadeci_id INT NOT NULL, emeliyyat_tarixi DATETIME DEFAULT GETDATE() NOT NULL, emeliyyat_novu NVARCHAR(100) NOT NULL, emeliyyat_obyekti NVARCHAR(100) NULL, obyekt_id INT NULL, tesvir NVARCHAR(MAX) NULL, ip_adresi NVARCHAR(45) NULL );
CREATE TABLE kateqoriyalar ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(100) UNIQUE NOT NULL, tesvir NVARCHAR(255) NULL, ana_kateqoriya_id INT NULL, aktivdir BIT DEFAULT 1 NOT NULL );
CREATE TABLE vahidler ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(50) UNIQUE NOT NULL, qisaltma NVARCHAR(10) NULL );
CREATE TABLE tedarukcüler ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(100) NOT NULL, vergi_nomresi NVARCHAR(20) NULL, elaqe_shexsi NVARCHAR(100) NULL, telefon NVARCHAR(20) NULL, unvan NVARCHAR(255) NULL, email NVARCHAR(100) NULL, aktivdir BIT DEFAULT 1 NOT NULL, qeyd NVARCHAR(500) NULL );
CREATE TABLE mehsullar ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(255) NOT NULL, barkod NVARCHAR(50) UNIQUE NULL, kateqoriya_id INT NOT NULL, vahid_id INT NOT NULL, alis_qiymeti DECIMAL(18, 2) NOT NULL, satis_qiymeti DECIMAL(18, 2) NOT NULL, minimum_stok INT DEFAULT 0 NOT NULL, cari_stok INT DEFAULT 0 NOT NULL, kritik_stok_seviyyesi INT NULL, tedarukcu_id INT NULL, tesvir NVARCHAR(MAX) NULL, aktivdir BIT DEFAULT 1 NOT NULL, silinib BIT DEFAULT 0 NOT NULL, yaradilma_tarixi DATETIME DEFAULT GETDATE() NOT NULL, son_deyisiklik DATETIME NULL, CONSTRAINT CHK_qiymet CHECK (satis_qiymeti >= alis_qiymeti) );
CREATE TABLE anbar_hereketleri ( id INT PRIMARY KEY IDENTITY(1,1), mehsul_id INT NOT NULL, hereket_novu NVARCHAR(50) NOT NULL, miqdar INT NOT NULL, hereket_tarixi DATETIME DEFAULT GETDATE() NOT NULL, istifadeci_id INT NOT NULL, sened_nomresi NVARCHAR(50) NULL, qeyd NVARCHAR(MAX) NULL, CONSTRAINT CHK_miqdar CHECK (miqdar > 0) );
CREATE TABLE musteriler ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(50) NOT NULL, soyad NVARCHAR(50) NOT NULL, telefon NVARCHAR(20) UNIQUE NOT NULL, unvan NVARCHAR(255) NULL, email NVARCHAR(100) NULL, nisye_limiti DECIMAL(18, 2) DEFAULT 0 NOT NULL, cari_nisye_borcu DECIMAL(18, 2) DEFAULT 0 NOT NULL, endirim_faizi DECIMAL(5,2) DEFAULT 0 NOT NULL, aktivdir BIT DEFAULT 1 NOT NULL, qeyd NVARCHAR(500) NULL, yaradilma_tarixi DATETIME DEFAULT GETDATE() NOT NULL );
CREATE TABLE satislar ( id INT PRIMARY KEY IDENTITY(1,1), satis_kodu AS ('SAT-' + RIGHT('000000' + CAST(id AS VARCHAR(6)), 6)), satis_tarixi DATETIME DEFAULT GETDATE() NOT NULL, musteri_id INT NULL, istifadeci_id INT NOT NULL, yekun_mebleg DECIMAL(18, 2) NOT NULL, odenmis_mebleg DECIMAL(18, 2) NOT NULL, qaliq_mebleg AS (yekun_mebleg - odenmis_mebleg), endirim_meblegi DECIMAL(18, 2) DEFAULT 0 NOT NULL, qaytarilib BIT DEFAULT 0 NOT NULL, legv_tarixi DATETIME NULL, legv_eden_istifadeci_id INT NULL, qeyd NVARCHAR(MAX) NULL, CONSTRAINT CHK_odenis CHECK (odenmis_mebleg >= 0 AND yekun_mebleg >= odenmis_mebleg) );
CREATE TABLE satis_mehsullari ( id INT PRIMARY KEY IDENTITY(1,1), satis_id INT NOT NULL, mehsul_id INT NOT NULL, miqdar INT NOT NULL, qiymet_bir_edede DECIMAL(18, 2) NOT NULL, endirim_meblegi DECIMAL(18, 2) DEFAULT 0 NOT NULL, yekun_satish_qiymeti AS (miqdar * qiymet_bir_edede - endirim_meblegi), qeyd NVARCHAR(255) NULL, CONSTRAINT CHK_satis_miqdar CHECK (miqdar > 0) );
CREATE TABLE odenis_novleri ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(50) UNIQUE NOT NULL, aktivdir BIT DEFAULT 1 NOT NULL, qeyd NVARCHAR(255) NULL );
CREATE TABLE odenisler ( id INT PRIMARY KEY IDENTITY(1,1), satis_id INT NOT NULL, odenis_nov_id INT NOT NULL, odenis_meblegi DECIMAL(18, 2) NOT NULL, odenis_tarixi DATETIME DEFAULT GETDATE() NOT NULL, kart_son_dord_reqem NVARCHAR(4) NULL, bank_ad NVARCHAR(100) NULL, qeyd NVARCHAR(255) NULL, CONSTRAINT CHK_odenis_mebleg CHECK (odenis_meblegi > 0) );
CREATE TABLE temir_statuslari ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(50) UNIQUE NOT NULL, siralama INT NOT NULL DEFAULT 0, icon_ad NVARCHAR(50) NULL );
CREATE TABLE temirler ( id INT PRIMARY KEY IDENTITY(1,1), temir_kodu AS ('TMR-' + RIGHT('000000' + CAST(id AS VARCHAR(6)), 6)), musteri_id INT NOT NULL, cihaz_adi NVARCHAR(100) NOT NULL, marka NVARCHAR(50) NULL, model NVARCHAR(50) NULL, seriya_nomresi NVARCHAR(100) NULL, problem_tesviri NVARCHAR(MAX) NOT NULL, qebul_tarixi DATETIME DEFAULT GETDATE() NOT NULL, texminen_tamamlama_tarixi DATETIME NULL, faktiki_tamamlama_tarixi DATETIME NULL, teslim_tarixi DATETIME NULL, status_id INT NOT NULL, temirci_id INT NULL, texminen_baxim_xerci DECIMAL(18,2) NULL, yekun_baxim_xerci DECIMAL(18,2) NULL, mexaric_qeyd_eden_istifadeci_id INT NULL, qeydler NVARCHAR(MAX) NULL, CONSTRAINT CHK_tarixler CHECK (texminen_tamamlama_tarixi >= qebul_tarixi) );
CREATE TABLE temir_hisseleri ( id INT PRIMARY KEY IDENTITY(1,1), temir_id INT NOT NULL, mehsul_id INT NOT NULL, miqdar INT NOT NULL, qiymet_bir_edede DECIMAL(18, 2) NOT NULL, total_qiymet AS (miqdar * qiymet_bir_edede), qeyd NVARCHAR(255) NULL, CONSTRAINT CHK_temir_miqdar CHECK (miqdar > 0) );
CREATE TABLE nisye_borclar ( id INT PRIMARY KEY IDENTITY(1,1), musteri_id INT NOT NULL, satish_id INT NULL, borc_meblegi DECIMAL(18, 2) NOT NULL, faiz_derecesi DECIMAL(5,2) DEFAULT 0 NOT NULL, toplam_borc_meblegi DECIMAL(18,2) NOT NULL, odenmis_mebleg DECIMAL(18,2) DEFAULT 0 NOT NULL, qaliq_borc AS (toplam_borc_meblegi - odenmis_mebleg), yaradilma_tarixi DATETIME DEFAULT GETDATE() NOT NULL, odeme_baslama_tarixi DATE NOT NULL, odeme_bitme_tarixi DATE NOT NULL, status NVARCHAR(50) NOT NULL, qeyd NVARCHAR(500) NULL, CONSTRAINT CHK_borc_tarix CHECK (odeme_bitme_tarixi > odeme_baslama_tarixi) );
CREATE TABLE odenis_cedveli ( id INT PRIMARY KEY IDENTITY(1,1), nisye_id INT NOT NULL, odenecek_mebleg DECIMAL(18,2) NOT NULL, planlanan_tarix DATE NOT NULL, odenis_tarixi DATETIME NULL, odenis_usulu NVARCHAR(50) NULL, odenmis_miqdar DECIMAL(18,2) DEFAULT 0 NOT NULL, status NVARCHAR(50) NOT NULL, qeyd NVARCHAR(255) NULL, CONSTRAINT CHK_odenis_miqdar CHECK (odenmis_miqdar >= 0) );
CREATE TABLE xidmetler ( id INT PRIMARY KEY IDENTITY(1,1), ad NVARCHAR(100) NOT NULL, qiymet DECIMAL(18, 2) NOT NULL, ortalama_vaxt INT NULL, tesvir NVARCHAR(MAX) NULL, aktivdir BIT DEFAULT 1 NOT NULL );
GO

-- Əlaqələrin (Foreign Keys) yaradılması
ALTER TABLE istifadeciler ADD CONSTRAINT FK_istifadeciler_rollar FOREIGN KEY (rol_id) REFERENCES rollar(id);
ALTER TABLE emeliyyat_jurnali ADD CONSTRAINT FK_emeliyyat_istifadeci FOREIGN KEY (istifadeci_id) REFERENCES istifadeciler(id);
ALTER TABLE mehsullar ADD CONSTRAINT FK_mehsullar_kateqoriya FOREIGN KEY (kateqoriya_id) REFERENCES kateqoriyalar(id);
ALTER TABLE mehsullar ADD CONSTRAINT FK_mehsullar_vahid FOREIGN KEY (vahid_id) REFERENCES vahidler(id);
-- ... və digər bütün ALTER TABLE ADD CONSTRAINT əmrləri ...
GO
PRINT '--- Cədvəllərin və Əlaqələrin Yaradılması Tamamlandı ---';