// <auto-generated />
using System;
using AzAgroPOS.Verilenler.Kontekst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzAgroPOS.Verilenler.Migrations
{
    [DbContext(typeof(AzAgroPOSDbContext))]
    [Migration("20250808210229_IstifadeciTemirElaqesiDuzelisi")]
    partial class IstifadeciTemirElaqesiDuzelisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IstifadeciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParolHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Istifadeciler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IstifadeciAdi = "admin",
                            ParolHash = "$2a$12$7k.z0VbLveS04B26Sg6Xoel5d1k3e.d6eJd.r4zGuL/l0U8h5V2qC",
                            RolId = 1,
                            TamAd = "Sistem Administratoru"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Mehsul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AlisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovcudSay")
                        .HasColumnType("int");

                    b.Property<decimal>("SatisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mehsullar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Çörək",
                            AlisQiymeti = 0.50m,
                            Barkod = "869000000001",
                            MovcudSay = 100,
                            SatisQiymeti = 0.70m,
                            StokKodu = "SK001"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Süd 1L",
                            AlisQiymeti = 2.00m,
                            Barkod = "869000000002",
                            MovcudSay = 50,
                            SatisQiymeti = 2.50m,
                            StokKodu = "SK002"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Yumurta (10 ədəd)",
                            AlisQiymeti = 2.80m,
                            Barkod = "869000000003",
                            MovcudSay = 200,
                            SatisQiymeti = 3.20m,
                            StokKodu = "SK003"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UmumiBorc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.NisyeHereketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmeliyyatNovu")
                        .HasColumnType("int");

                    b.Property<decimal>("Mebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("Qeyd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SatisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SatisId");

                    b.ToTable("NisyeHereketleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rollar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Kassir"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OdenisMetodu")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.SatisDetali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MehsulId")
                        .HasColumnType("int");

                    b.Property<int>("Miqdar")
                        .HasColumnType("int");

                    b.Property<decimal>("Qiymet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SatisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MehsulId");

                    b.HasIndex("SatisId");

                    b.ToTable("SatisDetallari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Temir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsciId")
                        .HasColumnType("int");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemTesviri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QebulTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TamamlanmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TemirXerci")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("YekunMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("TemirSifarisleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Rol", "Rol")
                        .WithMany("Istifadeciler")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.NisyeHereketi", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Satis", "Satis")
                        .WithMany()
                        .HasForeignKey("SatisId");

                    b.Navigation("Musteri");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.SatisDetali", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Mehsul", "Mehsul")
                        .WithMany()
                        .HasForeignKey("MehsulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Satis", "Satis")
                        .WithMany("SatisDetallari")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mehsul");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Temir", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Istifadeci", "Isci")
                        .WithMany("TemirSifarisleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.Navigation("TemirSifarisleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Rol", b =>
                {
                    b.Navigation("Istifadeciler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.Navigation("SatisDetallari");
                });
#pragma warning restore 612, 618
        }
    }
}
