// <auto-generated />
using System;
using AzAgroPOS.Verilenler.Kontekst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzAgroPOS.Verilenler.Migrations
{
    [DbContext(typeof(AzAgroPOSDbContext))]
    [Migration("20250906205606_AddKonfiqurasiyaTable")]
    partial class AddKonfiqurasiyaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSened", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Qeydler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenedNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TedarukcuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TehvilTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TedarukcuId");

                    b.ToTable("AlisSenetleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSenedSetiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisSenedId")
                        .HasColumnType("int");

                    b.Property<int?>("AlisSifarisSetiriId")
                        .HasColumnType("int");

                    b.Property<decimal>("BirVahidQiymet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CemiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MehsulId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miqdar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AlisSenedId");

                    b.HasIndex("AlisSifarisSetiriId");

                    b.HasIndex("MehsulId");

                    b.ToTable("AlisSenedSetirleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSifaris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FaktikiTehvilTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GozlenilenTehvilTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Qeydler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifarisNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TedarukcuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TedarukcuId");

                    b.ToTable("AlisSifarisleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSifarisSetiri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisSifarisId")
                        .HasColumnType("int");

                    b.Property<decimal>("BirVahidQiymet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("CemiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MehsulId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miqdar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("TehvilAlinanMiqdar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlisSifarisId");

                    b.HasIndex("MehsulId");

                    b.ToTable("AlisSifarisSetirleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Brend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<string>("LoqoFaylYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Olke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Tesvir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vebsayt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brendler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ənənəvi",
                            Aktivdir = true,
                            Olke = "Azərbaycan",
                            Silinib = false,
                            Tesvir = "Yerli brend",
                            Vebsayt = "www.enanevi.az"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Fresh",
                            Aktivdir = true,
                            Olke = "Azərbaycan",
                            Silinib = false,
                            Tesvir = "Təzə məhsullar",
                            Vebsayt = "www.fresh.az"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "CleanHome",
                            Aktivdir = true,
                            Olke = "Almaniya",
                            Silinib = false,
                            Tesvir = "Təmizlik vasitələri",
                            Vebsayt = "www.cleanhome.de"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.EmeliyyatJurnali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CədvəlAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmeliyyatNovu")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmeliyyatTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IstifadeciId")
                        .HasColumnType("int");

                    b.Property<int>("ObyektId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("EmeliyyatJurnallari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Isci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankMəlumatları")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IseBaslamaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("QeydiyyatUnvani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("SistemIstifadecisiId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SvsNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vezife")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SistemIstifadecisiId");

                    b.ToTable("Isciler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankMəlumatları = "IBAN: AZ12NABZ0000000012345678",
                            Departament = "Satış",
                            DogumTarixi = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.mammadov@example.com",
                            IseBaslamaTarixi = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Maas = 1200.00m,
                            QeydiyyatUnvani = "Bakı şəh., Nərimanov r-nu",
                            Silinib = false,
                            Status = 1,
                            SvsNo = "AZE12345678",
                            TamAd = "Əli Məmmədov",
                            TelefonNomresi = "+994501234567",
                            Unvan = "Bakı şəh., Nərimanov r-nu, Sədərək m/s",
                            Vezife = "Kassir"
                        },
                        new
                        {
                            Id = 2,
                            BankMəlumatları = "IBAN: AZ87NABZ0000000087654321",
                            Departament = "İdarəetmə",
                            DogumTarixi = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nargiz.quliyeva@example.com",
                            IseBaslamaTarixi = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Maas = 1500.00m,
                            QeydiyyatUnvani = "Bakı şəh., Xətai r-nu",
                            Silinib = false,
                            Status = 1,
                            SvsNo = "AZE87654321",
                            TamAd = "Nərgiz Quliyeva",
                            TelefonNomresi = "+994552345678",
                            Unvan = "Bakı şəh., Xətai r-nu, Mərdəkan m/s",
                            Vezife = "Menecer"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciIzni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslamaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int>("IzinGunu")
                        .HasColumnType("int");

                    b.Property<int>("IzinNovu")
                        .HasColumnType("int");

                    b.Property<string>("Qeydler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sebeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TesdiqEdenIsciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.HasIndex("TesdiqEdenIsciId");

                    b.ToTable("IsciIznleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciPerformans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Emsallar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<string>("QeydDovru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qeydler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qiymet")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<string>("Teklifler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("IsciPerformanslari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IstifadeciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParolHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Istifadeciler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IstifadeciAdi = "admin",
                            ParolHash = "$2a$11$wvv2PHlk9LWlv4vuz3eEBl.ynUDwxFQSIHWle5nHfS3sL7hTkTQPG",
                            RolId = 1,
                            Silinib = false,
                            TamAd = "Sistem Administratoru"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Kateqoriya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Tesvir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kateqoriyalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Qida Məhsulları",
                            Aktivdir = true,
                            Silinib = false,
                            Tesvir = "Yemək və içki məhsulları"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Təmizlik Vasitələri",
                            Aktivdir = true,
                            Silinib = false,
                            Tesvir = "Ev təmizliyi üçün vasitələr"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Şəxsi Gigiyena",
                            Aktivdir = true,
                            Silinib = false,
                            Tesvir = "Şəxsi gigiyena məhsulları"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Konfiqurasiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deyer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qrup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Tesvir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Konfiqurasiyalar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Mehsul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<decimal>("AlisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrendId")
                        .HasColumnType("int");

                    b.Property<int?>("KateqoriyaId")
                        .HasColumnType("int");

                    b.Property<int>("MinimumStok")
                        .HasColumnType("int");

                    b.Property<int>("MovcudSay")
                        .HasColumnType("int");

                    b.Property<int>("OlcuVahidi")
                        .HasColumnType("int");

                    b.Property<decimal>("PerakendeSatisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SekilYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("StokKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TedarukcuId")
                        .HasColumnType("int");

                    b.Property<decimal>("TekEdedSatisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TopdanSatisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BrendId");

                    b.HasIndex("KateqoriyaId");

                    b.HasIndex("TedarukcuId");

                    b.ToTable("Mehsullar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Çörək",
                            Aktivdir = true,
                            AlisQiymeti = 0.50m,
                            Barkod = "869000000001",
                            MinimumStok = 0,
                            MovcudSay = 100,
                            OlcuVahidi = 1,
                            PerakendeSatisQiymeti = 0.70m,
                            Silinib = false,
                            StokKodu = "SK001",
                            TekEdedSatisQiymeti = 0m,
                            TopdanSatisQiymeti = 0m
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Süd 1L",
                            Aktivdir = true,
                            AlisQiymeti = 2.00m,
                            Barkod = "869000000002",
                            MinimumStok = 0,
                            MovcudSay = 50,
                            OlcuVahidi = 3,
                            PerakendeSatisQiymeti = 2.50m,
                            Silinib = false,
                            StokKodu = "SK002",
                            TekEdedSatisQiymeti = 0m,
                            TopdanSatisQiymeti = 0m
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Yumurta (10 ədəd)",
                            Aktivdir = true,
                            AlisQiymeti = 2.80m,
                            Barkod = "869000000003",
                            MinimumStok = 0,
                            MovcudSay = 200,
                            OlcuVahidi = 5,
                            PerakendeSatisQiymeti = 3.20m,
                            Silinib = false,
                            StokKodu = "SK003",
                            TekEdedSatisQiymeti = 0m,
                            TopdanSatisQiymeti = 0m
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("KreditLimiti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UmumiBorc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.NisyeHereketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmeliyyatNovu")
                        .HasColumnType("int");

                    b.Property<decimal>("Mebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("Qeyd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SatisId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SatisId");

                    b.ToTable("NisyeHereketleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Novbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BaglanmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BaslangicMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FaktikiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GozlenilenMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("Novbeler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Qaytarma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KassirId")
                        .HasColumnType("int");

                    b.Property<int>("SatisId")
                        .HasColumnType("int");

                    b.Property<string>("Sebeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KassirId");

                    b.HasIndex("SatisId");

                    b.ToTable("Qaytarmalar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.QaytarmaDetali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MehsulId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miqdar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QaytarmaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qiymet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MehsulId");

                    b.HasIndex("QaytarmaId");

                    b.ToTable("QaytarmaDetallari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Rollar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            Silinib = false
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Kassir",
                            Silinib = false
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("NovbeId")
                        .HasColumnType("int");

                    b.Property<int>("OdenisMetodu")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("NovbeId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.SatisDetali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MehsulId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miqdar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Qiymet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SatisId")
                        .HasColumnType("int");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MehsulId");

                    b.HasIndex("SatisId");

                    b.ToTable("SatisDetallari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Tedarukcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<string>("BankHesabi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tedarukculer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ənənəvi Bakery",
                            Aktivdir = true,
                            BankHesabi = "IBAN: AZ12NABZ0000000012345678",
                            Email = "info@enanavi-bakery.az",
                            Silinib = false,
                            Telefon = "+994123456789",
                            Unvan = "Bakı şəh., Nəsimi r-nu, Cavid prospekti 45",
                            Voen = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Fresh Dairy Products",
                            Aktivdir = true,
                            BankHesabi = "IBAN: AZ87NABZ0000000087654321",
                            Email = "orders@fresh-dairy.az",
                            Silinib = false,
                            Telefon = "+994181234567",
                            Unvan = "Sumqayıt şəh., Sənaye rayonu, Zavod küçəsi 12",
                            Voen = "0987654321"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.TedarukcuOdeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlisSenedId")
                        .HasColumnType("int");

                    b.Property<string>("BankMelumatlari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Mebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("OdemeNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OdemeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdemeUsulu")
                        .HasColumnType("int");

                    b.Property<string>("Qeydler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TedarukcuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YaradilmaTarixi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlisSenedId");

                    b.HasIndex("TedarukcuId");

                    b.ToTable("TedarukcuOdemeleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Temir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsciId")
                        .HasColumnType("int");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemTesviri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QebulTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeriyaNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ServisHaqqi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Silinib")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TamamlanmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TemirXerci")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("YekunMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ZemanetMuddeti")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("TemirSifarisleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSened", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Tedarukcu", "Tedarukcu")
                        .WithMany("AlisSenetleri")
                        .HasForeignKey("TedarukcuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tedarukcu");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSenedSetiri", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.AlisSened", "AlisSened")
                        .WithMany("SenedSetirleri")
                        .HasForeignKey("AlisSenedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.AlisSifarisSetiri", "AlisSifarisSetiri")
                        .WithMany()
                        .HasForeignKey("AlisSifarisSetiriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AzAgroPOS.Varliglar.Mehsul", "Mehsul")
                        .WithMany()
                        .HasForeignKey("MehsulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlisSened");

                    b.Navigation("AlisSifarisSetiri");

                    b.Navigation("Mehsul");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSifaris", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Tedarukcu", "Tedarukcu")
                        .WithMany("AlisSifarisleri")
                        .HasForeignKey("TedarukcuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tedarukcu");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSifarisSetiri", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.AlisSifaris", "AlisSifaris")
                        .WithMany("SifarisSetirleri")
                        .HasForeignKey("AlisSifarisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Mehsul", "Mehsul")
                        .WithMany()
                        .HasForeignKey("MehsulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlisSifaris");

                    b.Navigation("Mehsul");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Isci", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Istifadeci", "SistemIstifadecisi")
                        .WithMany()
                        .HasForeignKey("SistemIstifadecisiId");

                    b.Navigation("SistemIstifadecisi");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciIzni", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Isci", "Isci")
                        .WithMany("IzinQeydleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Isci", "TesdiqEdenIsci")
                        .WithMany()
                        .HasForeignKey("TesdiqEdenIsciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Isci");

                    b.Navigation("TesdiqEdenIsci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciPerformans", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Isci", "Isci")
                        .WithMany("PerformansQeydleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Rol", "Rol")
                        .WithMany("Istifadeciler")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Mehsul", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Brend", "Brend")
                        .WithMany("Mehsullar")
                        .HasForeignKey("BrendId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzAgroPOS.Varliglar.Kateqoriya", "Kateqoriya")
                        .WithMany("Mehsullar")
                        .HasForeignKey("KateqoriyaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzAgroPOS.Varliglar.Tedarukcu", "Tedarukcu")
                        .WithMany()
                        .HasForeignKey("TedarukcuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brend");

                    b.Navigation("Kateqoriya");

                    b.Navigation("Tedarukcu");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.NisyeHereketi", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Satis", "Satis")
                        .WithMany()
                        .HasForeignKey("SatisId");

                    b.Navigation("Musteri");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Novbe", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Istifadeci", "Isci")
                        .WithMany("Novbeler")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Qaytarma", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Istifadeci", "Kassir")
                        .WithMany()
                        .HasForeignKey("KassirId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Satis", "Satis")
                        .WithMany("Qaytarmalar")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kassir");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.QaytarmaDetali", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Mehsul", "Mehsul")
                        .WithMany()
                        .HasForeignKey("MehsulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Qaytarma", "Qaytarma")
                        .WithMany("QaytarmaDetallari")
                        .HasForeignKey("QaytarmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mehsul");

                    b.Navigation("Qaytarma");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.HasOne("AzAgroPOS.Varliglar.Novbe", "Novbe")
                        .WithMany("Satislar")
                        .HasForeignKey("NovbeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Novbe");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.SatisDetali", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Mehsul", "Mehsul")
                        .WithMany()
                        .HasForeignKey("MehsulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Satis", "Satis")
                        .WithMany("SatisDetallari")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mehsul");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.TedarukcuOdeme", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.AlisSened", "AlisSened")
                        .WithMany("Odemeler")
                        .HasForeignKey("AlisSenedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzAgroPOS.Varliglar.Tedarukcu", "Tedarukcu")
                        .WithMany("Odemeler")
                        .HasForeignKey("TedarukcuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlisSened");

                    b.Navigation("Tedarukcu");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Temir", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Istifadeci", "Isci")
                        .WithMany("TemirSifarisleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSened", b =>
                {
                    b.Navigation("Odemeler");

                    b.Navigation("SenedSetirleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.AlisSifaris", b =>
                {
                    b.Navigation("SifarisSetirleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Brend", b =>
                {
                    b.Navigation("Mehsullar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Isci", b =>
                {
                    b.Navigation("IzinQeydleri");

                    b.Navigation("PerformansQeydleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.Navigation("Novbeler");

                    b.Navigation("TemirSifarisleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Kateqoriya", b =>
                {
                    b.Navigation("Mehsullar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Novbe", b =>
                {
                    b.Navigation("Satislar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Qaytarma", b =>
                {
                    b.Navigation("QaytarmaDetallari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Rol", b =>
                {
                    b.Navigation("Istifadeciler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.Navigation("Qaytarmalar");

                    b.Navigation("SatisDetallari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Tedarukcu", b =>
                {
                    b.Navigation("AlisSenetleri");

                    b.Navigation("AlisSifarisleri");

                    b.Navigation("Odemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
