// <auto-generated />
using System;
using AzAgroPOS.Verilenler.Kontekst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzAgroPOS.Verilenler.Migrations
{
    [DbContext(typeof(AzAgroPOSDbContext))]
    [Migration("20250905174959_isciidareetmemodulu")]
    partial class isciidareetmemodulu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzAgroPOS.Varliglar.Isci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankMəlumatları")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarixi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IseBaslamaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("QeydiyyatUnvani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SvsNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vezife")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Isciler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankMəlumatları = "IBAN: AZ12NABZ0000000012345678",
                            Departament = "Satış",
                            DogumTarixi = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.mammadov@example.com",
                            IseBaslamaTarixi = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Maas = 1200.00m,
                            QeydiyyatUnvani = "Bakı şəh., Nərimanov r-nu",
                            Status = 1,
                            SvsNo = "AZE12345678",
                            TamAd = "Əli Məmmədov",
                            TelefonNomresi = "+994501234567",
                            Unvan = "Bakı şəh., Nərimanov r-nu, Sədərək m/s",
                            Vezife = "Kassir"
                        },
                        new
                        {
                            Id = 2,
                            BankMəlumatları = "IBAN: AZ87NABZ0000000087654321",
                            Departament = "İdarəetmə",
                            DogumTarixi = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nargiz.quliyeva@example.com",
                            IseBaslamaTarixi = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Maas = 1500.00m,
                            QeydiyyatUnvani = "Bakı şəh., Xətai r-nu",
                            Status = 1,
                            SvsNo = "AZE87654321",
                            TamAd = "Nərgiz Quliyeva",
                            TelefonNomresi = "+994552345678",
                            Unvan = "Bakı şəh., Xətai r-nu, Mərdəkan m/s",
                            Vezife = "Menecer"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciIzni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslamaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitmeTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int>("IzinGunu")
                        .HasColumnType("int");

                    b.Property<int>("IzinNovu")
                        .HasColumnType("int");

                    b.Property<string>("Qeydler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sebeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TesdiqEdenIsciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TesdiqTarixi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.HasIndex("TesdiqEdenIsciId");

                    b.ToTable("IsciIznleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciPerformans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Emsallar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<string>("QeydDovru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qeydler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qiymet")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<string>("Teklifler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("IsciPerformanslari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("IstifadeciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParolHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Istifadeciler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IstifadeciAdi = "admin",
                            ParolHash = "$2a$11$wvv2PHlk9LWlv4vuz3eEBl.ynUDwxFQSIHWle5nHfS3sL7hTkTQPG",
                            RolId = 1,
                            TamAd = "Sistem Administratoru"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Mehsul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktivdir")
                        .HasColumnType("bit");

                    b.Property<decimal>("AlisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovcudSay")
                        .HasColumnType("int");

                    b.Property<int>("OlcuVahidi")
                        .HasColumnType("int");

                    b.Property<decimal>("PerakendeSatisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StokKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TekEdedSatisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TopdanSatisQiymeti")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Mehsullar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Çörək",
                            Aktivdir = true,
                            AlisQiymeti = 0.50m,
                            Barkod = "869000000001",
                            MovcudSay = 100,
                            OlcuVahidi = 1,
                            PerakendeSatisQiymeti = 0.70m,
                            StokKodu = "SK001",
                            TekEdedSatisQiymeti = 0m,
                            TopdanSatisQiymeti = 0m
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Süd 1L",
                            Aktivdir = true,
                            AlisQiymeti = 2.00m,
                            Barkod = "869000000002",
                            MovcudSay = 50,
                            OlcuVahidi = 3,
                            PerakendeSatisQiymeti = 2.50m,
                            StokKodu = "SK002",
                            TekEdedSatisQiymeti = 0m,
                            TopdanSatisQiymeti = 0m
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Yumurta (10 ədəd)",
                            Aktivdir = true,
                            AlisQiymeti = 2.80m,
                            Barkod = "869000000003",
                            MovcudSay = 200,
                            OlcuVahidi = 5,
                            PerakendeSatisQiymeti = 3.20m,
                            StokKodu = "SK003",
                            TekEdedSatisQiymeti = 0m,
                            TopdanSatisQiymeti = 0m
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("KreditLimiti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNomresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UmumiBorc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.NisyeHereketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmeliyyatNovu")
                        .HasColumnType("int");

                    b.Property<decimal>("Mebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("Qeyd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SatisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SatisId");

                    b.ToTable("NisyeHereketleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Novbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcilmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BaglanmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BaslangicMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FaktikiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GozlenilenMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("IsciId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("Novbeler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rollar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Kassir"
                        });
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("NovbeId")
                        .HasColumnType("int");

                    b.Property<int>("OdenisMetodu")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarix")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("NovbeId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.SatisDetali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MehsulId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miqdar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Qiymet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SatisId")
                        .HasColumnType("int");

                    b.Property<decimal>("UmumiMebleg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MehsulId");

                    b.HasIndex("SatisId");

                    b.ToTable("SatisDetallari");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Temir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsciId")
                        .HasColumnType("int");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemTesviri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QebulTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TamamlanmaTarixi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TemirXerci")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("YekunMebleg")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IsciId");

                    b.ToTable("TemirSifarisleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciIzni", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Isci", "Isci")
                        .WithMany("IzinQeydleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Isci", "TesdiqEdenIsci")
                        .WithMany()
                        .HasForeignKey("TesdiqEdenIsciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Isci");

                    b.Navigation("TesdiqEdenIsci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.IsciPerformans", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Isci", "Isci")
                        .WithMany("PerformansQeydleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Isci", "Isci")
                        .WithOne("SistemIstifadecisi")
                        .HasForeignKey("AzAgroPOS.Varliglar.Istifadeci", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Rol", "Rol")
                        .WithMany("Istifadeciler")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Isci");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.NisyeHereketi", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Satis", "Satis")
                        .WithMany()
                        .HasForeignKey("SatisId");

                    b.Navigation("Musteri");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Novbe", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Istifadeci", "Isci")
                        .WithMany("Novbeler")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId");

                    b.HasOne("AzAgroPOS.Varliglar.Novbe", "Novbe")
                        .WithMany("Satislar")
                        .HasForeignKey("NovbeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Novbe");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.SatisDetali", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Mehsul", "Mehsul")
                        .WithMany()
                        .HasForeignKey("MehsulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzAgroPOS.Varliglar.Satis", "Satis")
                        .WithMany("SatisDetallari")
                        .HasForeignKey("SatisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mehsul");

                    b.Navigation("Satis");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Temir", b =>
                {
                    b.HasOne("AzAgroPOS.Varliglar.Istifadeci", "Isci")
                        .WithMany("TemirSifarisleri")
                        .HasForeignKey("IsciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Isci");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Isci", b =>
                {
                    b.Navigation("IzinQeydleri");

                    b.Navigation("PerformansQeydleri");

                    b.Navigation("SistemIstifadecisi");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Istifadeci", b =>
                {
                    b.Navigation("Novbeler");

                    b.Navigation("TemirSifarisleri");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Novbe", b =>
                {
                    b.Navigation("Satislar");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Rol", b =>
                {
                    b.Navigation("Istifadeciler");
                });

            modelBuilder.Entity("AzAgroPOS.Varliglar.Satis", b =>
                {
                    b.Navigation("SatisDetallari");
                });
#pragma warning restore 612, 618
        }
    }
}
