using AzAgroPOS.DAL.Helpers;
using AzAgroPOS.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;

namespace AzAgroPOS.DAL
{
    public class MehsulDAL
    {
        private readonly string _connectionString = DatabaseHelper.GetConnectionString();

        public List<Mehsul> GetAll()
        {
            var mehsullar = new List<Mehsul>();
            using (var connection = new SqlConnection(_connectionString))
            {
                var query = @"SELECT 
                                m.id, m.ad, m.barkod, m.alis_qiymeti, m.satis_qiymeti, m.minimum_stok, m.cari_stok, m.tesvir, m.aktivdir, m.silinib, m.IsAutoGenerated,
                                k.ad as KateqoriyaAdi, v.ad as VahidAdi, t.ad as TedarukcuAdi,
                                m.kateqoriya_id, m.vahid_id, m.tedarukcu_id
                              FROM mehsullar m
                              LEFT JOIN kateqoriyalar k ON m.kateqoriya_id = k.id
                              LEFT JOIN vahidler v ON m.vahid_id = v.id
                              LEFT JOIN tedarukcüler t ON m.tedarukcu_id = t.id
                              WHERE m.silinib = 0";
                var command = new SqlCommand(query, connection);
                try
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            mehsullar.Add(MapMehsul(reader));
                        }
                    }
                }
                catch (Exception ex) { throw new Exception("Məhsullar gətirilərkən xəta baş verdi.", ex); }
            }
            return mehsullar;
        }

        public Mehsul GetById(int id)
        {
            using (var conn = new SqlConnection(_connectionString))
            {
                var query = "SELECT * FROM mehsullar WHERE id = @id";
                var command = new SqlCommand(query, conn);
                command.Parameters.AddWithValue("@id", id);
                try
                {
                    conn.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            return MapMehsul(reader);
                        }
                    }
                }
                catch (Exception ex) { throw; }
            }
            return null;
        }

        public Mehsul GetByBarcode(string barkod)
        {
            Mehsul mehsul = null;
            using (var connection = new SqlConnection(_connectionString))
            {
                var query = "SELECT * FROM mehsullar WHERE barkod = @barkod AND aktivdir = 1 AND silinib = 0";
                var command = new SqlCommand(query, connection);
                command.Parameters.Add("@barkod", SqlDbType.NVarChar).Value = barkod;
                try
                {
                    connection.Open();
                    using (var reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            mehsul = MapMehsul(reader);
                        }
                    }
                }
                catch (Exception ex) { throw; }
            }
            return mehsul;
        }

        public int Add(Mehsul mehsul)
        {
            using (var connection = new SqlConnection(_connectionString))
            {
                var query = "INSERT INTO mehsullar (ad, barkod, kateqoriya_id, vahid_id, alis_qiymeti, satis_qiymeti, minimum_stok, tedarukcu_id, tesvir, aktivdir, IsAutoGenerated) " +
                            "VALUES (@ad, @barkod, @kateqoriya_id, @vahid_id, @alis_qiymeti, @satis_qiymeti, @minimum_stok, @tedarukcu_id, @tesvir, @aktivdir, @isAutoGenerated); SELECT SCOPE_IDENTITY();";
                var command = new SqlCommand(query, connection);
                AddParameters(command, mehsul);
                try
                {
                    connection.Open();
                    return Convert.ToInt32(command.ExecuteScalar());
                }
                catch (Exception ex)
                {
                    throw new Exception("Məhsul əlavə edilərkən verilənlər bazasında xəta baş verdi.", ex);
                }
            }
        }

        public bool Update(Mehsul mehsul)
        {
            using (var connection = new SqlConnection(_connectionString))
            {
                var query = "UPDATE mehsullar SET ad=@ad, barkod=@barkod, kateqoriya_id=@kateqoriya_id, vahid_id=@vahid_id, " +
                            "alis_qiymeti=@alis_qiymeti, satis_qiymeti=@satis_qiymeti, minimum_stok=@minimum_stok, " +
                            "tedarukcu_id=@tedarukcu_id, tesvir=@tesvir, aktivdir=@aktivdir, son_deyisiklik=GETDATE() WHERE id=@id";
                var command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@id", mehsul.Id);
                AddParameters(command, mehsul);
                try
                {
                    connection.Open();
                    return command.ExecuteNonQuery() > 0;
                }
                catch (Exception ex) { throw; }
            }
        }

        public bool Delete(int mehsulId)
        {
            using (var connection = new SqlConnection(_connectionString))
            {
                var query = "UPDATE mehsullar SET silinib = 1, aktivdir = 0, son_deyisiklik=GETDATE() WHERE id=@id";
                var command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@id", mehsulId);
                try
                {
                    connection.Open();
                    return command.ExecuteNonQuery() > 0;
                }
                catch (Exception ex) { throw; }
            }
        }

        public int GetLastProductId()
        {
            using (var conn = new SqlConnection(_connectionString))
            {
                var query = "SELECT ISNULL(IDENT_CURRENT('mehsullar'), 0);";
                var command = new SqlCommand(query, conn);
                try
                {
                    conn.Open();
                    return Convert.ToInt32(command.ExecuteScalar());
                }
                catch (Exception) { return 0; }
            }
        }

        public bool BarcodeExists(string barcode)
        {
            using (var conn = new SqlConnection(_connectionString))
            {
                var query = "SELECT COUNT(1) FROM mehsullar WHERE barkod = @barcode";
                var command = new SqlCommand(query, conn);
                command.Parameters.Add("@barcode", SqlDbType.NVarChar).Value = barcode;
                try
                {
                    conn.Open();
                    return (int)command.ExecuteScalar() > 0;
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                    return true;
                }
            }
        }

        private void AddParameters(SqlCommand command, Mehsul mehsul)
        {
            command.Parameters.Add("@ad", SqlDbType.NVarChar).Value = mehsul.Ad;
            command.Parameters.Add("@barkod", SqlDbType.NVarChar).Value = (object)mehsul.Barkod ?? DBNull.Value;
            command.Parameters.Add("@kateqoriya_id", SqlDbType.Int).Value = mehsul.KateqoriyaId;
            command.Parameters.Add("@vahid_id", SqlDbType.Int).Value = mehsul.VahidId;
            command.Parameters.Add("@alis_qiymeti", SqlDbType.Decimal).Value = mehsul.AlisQiymeti;
            command.Parameters.Add("@satis_qiymeti", SqlDbType.Decimal).Value = mehsul.SatisQiymeti;
            command.Parameters.Add("@minimum_stok", SqlDbType.Int).Value = mehsul.MinimumStok;
            command.Parameters.Add("@tedarukcu_id", SqlDbType.Int).Value = (object)mehsul.TedarukcuId ?? DBNull.Value;
            command.Parameters.Add("@tesvir", SqlDbType.NVarChar).Value = (object)mehsul.Tesvir ?? DBNull.Value;
            command.Parameters.Add("@aktivdir", SqlDbType.Bit).Value = mehsul.Aktivdir;
            // IsAutoGenerated parametri yalnız Add zamanı lazımdır, amma burada da ola bilər.
            if (command.CommandText.Contains("@isAutoGenerated"))
            {
                command.Parameters.Add("@isAutoGenerated", SqlDbType.Bit).Value = mehsul.IsAutoGenerated;
            }
        }

        private Mehsul MapMehsul(SqlDataReader reader)
        {
            var mehsul = new Mehsul
            {
                Id = (int)reader["id"],
                Ad = reader["ad"].ToString(),
                Barkod = reader["barkod"]?.ToString(),
                KateqoriyaId = (int)reader["kateqoriya_id"],
                VahidId = (int)reader["vahid_id"],
                AlisQiymeti = (decimal)reader["alis_qiymeti"],
                SatisQiymeti = (decimal)reader["satis_qiymeti"],
                MinimumStok = (int)reader["minimum_stok"],
                CariStok = (int)reader["cari_stok"],
                TedarukcuId = reader["tedarukcu_id"] as int?,
                Tesvir = reader["tesvir"]?.ToString(),
                Aktivdir = (bool)reader["aktivdir"],
                Silinib = (bool)reader["silinib"],
                IsAutoGenerated = ColumnExists(reader, "IsAutoGenerated") && (bool)reader["IsAutoGenerated"]
            };

            // JOIN-dan gələn adları da mənimsədirik
            if (ColumnExists(reader, "KateqoriyaAdi")) mehsul.KateqoriyaAdi = reader["KateqoriyaAdi"].ToString();
            if (ColumnExists(reader, "VahidAdi")) mehsul.VahidAdi = reader["VahidAdi"].ToString();

            return mehsul;
        }

        private bool ColumnExists(SqlDataReader reader, string columnName)
        {
            return reader.GetSchemaTable().Rows.OfType<DataRow>().Any(row => row["ColumnName"].ToString().Equals(columnName, StringComparison.OrdinalIgnoreCase));
        }
    }
}