using AzAgroPOS.BLL.Helpers;
using AzAgroPOS.DAL;
using AzAgroPOS.Entities;
using System;
using System.Collections.Generic;

namespace AzAgroPOS.BLL
{
    /// <summary>
    /// Məhsullarla bağlı biznes məntiqini həyata keçirən sinif.
    /// </summary>
    public class MehsulBLL
    {
        private readonly MehsulDAL _dal = new MehsulDAL();

        /// <summary>
        /// Bütün aktiv məhsulların siyahısını qaytarır.
        /// </summary>
        /// <returns>Məhsullar siyahısı.</returns>
        public List<Mehsul> GetAll() => _dal.GetAll();

        /// <summary>
        /// Barkod üzrə məhsul məlumatını qaytarır.
        /// </summary>
        /// <param name="barkod">Axtarılacaq barkod.</param>
        /// <returns>Tapılsa Mehsul obyekti, əks halda null.</returns>
        public Mehsul GetByBarcode(string barkod)
        {
            if (string.IsNullOrWhiteSpace(barkod))
            {
                return null;
            }
            return _dal.GetByBarcode(barkod);
        }

        /// <summary>
        /// Yeni məhsul yaradır və əməliyyatı jurnala yazır.
        /// </summary>
        /// <param name="mehsul">Əlavə ediləcək məhsul obyekti.</param>
        /// <param name="emeliyyatiEden">Əməliyyatı icra edən istifadəçi.</param>
        /// <param name="message">Nəticə mesajı.</param>
        /// <returns>Əməliyyatın uğurlu olub-olmadığı.</returns>
        public bool Add(Mehsul mehsul, Istifadeci emeliyyatiEden, out string message)
        {
            if (string.IsNullOrWhiteSpace(mehsul.Ad))
            {
                message = "Məhsul adı boş ola bilməz.";
                return false;
            }
            if (mehsul.SatisQiymeti < mehsul.AlisQiymeti)
            {
                message = "Satış qiyməti alış qiymətindən az ola bilməz.";
                return false;
            }

            int newId = _dal.Add(mehsul);
            if (newId > 0)
            {
                message = "Məhsul uğurla əlavə edildi.";
                AuditLogger.Log(emeliyyatiEden.Id, "Məhsul Əlavə Etdi", $"Yeni məhsul: {mehsul.Ad} (ID: {newId}, Barkod: {mehsul.Barkod})");
                return true;
            }
            /// <summary>
            /// Əgər barkod boşdursa, avtomatik yaradır.
            /// </summary>

            if (string.IsNullOrWhiteSpace(mehsul.Barkod))
            {
                mehsul.Barkod = GenerateNewBarcode();
                mehsul.IsAutoGenerated = true;
            }
            else
            {
                mehsul.IsAutoGenerated = false;

            }
            
            message = "Məhsul əlavə edilərkən xəta baş verdi.";
            return false;
        }

        /// <summary>
        /// Mövcud məhsulun məlumatlarını yeniləyir və əməliyyatı jurnala yazır.
        /// </summary>
        /// <param name="mehsul">Yenilənəcək məhsul obyekti.</param>
        /// <param name="emeliyyatiEden">Əməliyyatı icra edən istifadəçi.</param>
        /// <param name="message">Nəticə mesajı.</param>
        /// <returns>Əməliyyatın uğurlu olub-olmadığı.</returns>
        public bool Update(Mehsul mehsul, Istifadeci emeliyyatiEden, out string message)
        {
            if (mehsul.Id <= 0)
            {
                message = "Yeniləmək üçün məhsul seçilməyib.";
                return false;
            }
            if (string.IsNullOrWhiteSpace(mehsul.Ad))
            {
                message = "Məhsul adı boş ola bilməz.";
                return false;
            }

            if (_dal.Update(mehsul))
            {
                message = "Məhsul uğurla yeniləndi.";
                AuditLogger.Log(emeliyyatiEden.Id, "Məhsul Yenilədi",
                    $"Məhsul: {mehsul.Ad} (ID: {mehsul.Id}). " +
                    $"Yeni qiymətlər: Alış={mehsul.AlisQiymeti}, Satış={mehsul.SatisQiymeti}");
                return true;
            }

            message = "Məhsul yenilənərkən xəta baş verdi.";
            return false;
        }
        /// <summary>
        /// "AZP-XXXXXX" formatında yeni və unikal barkod yaradır.
        /// </summary>
        private string GenerateNewBarcode()
        {
            int lastId = _dal.GetLastProductId();
            int nextId = lastId + 1;
            return $"AZP-{nextId:D6}";
        }

        /// <summary>
        /// Məhsulu sistemdən silir (deaktiv edir) və əməliyyatı jurnala yazır.
        /// </summary>
        /// <param name="mehsulId">Silinəcək məhsulun ID-si.</param>
        /// <param name="emeliyyatiEden">Əməliyyatı icra edən istifadəçi.</param>
        /// <param name="message">Nəticə mesajı.</param>
        /// <returns>Əməliyyatın uğurlu olub-olmadığı.</returns>
        public bool Delete(int mehsulId, Istifadeci emeliyyatiEden, out string message)
        {
            if (mehsulId <= 0)
            {
                message = "Silmək üçün məhsul seçilməyib.";
                return false;
            }

            // Əvvəlcə məhsul məlumatlarını alırıq ki, jurnalda istifadə edək
            var mehsul = _dal.GetById(mehsulId);
            string mehsulAdi = mehsul?.Ad ?? "Naməlum";

            if (_dal.Delete(mehsulId))
            {
                message = "Məhsul uğurla silindi.";
                AuditLogger.Log(emeliyyatiEden.Id, "Məhsul Silindi",
                    $"Məhsul: {mehsulAdi} (ID: {mehsulId})");
                return true;
            }

            message = "Məhsul silinərkən xəta baş verdi.";
            return false;
        }
  
        /// <summary>
        /// ID üzrə məhsul məlumatını qaytarır.
        /// </summary>
        /// <param name="id">Axtarılan məhsulun ID-si.</param>
        /// <returns>Tapılsa Mehsul obyekti, əks halda null.</returns>
        public Mehsul GetById(int id)
        {
            if (id <= 0) return null;
            return _dal.GetById(id);
        }
    }
}